### ISSUE TITLE
Couldn't find a tree builder with the Features you requested: xml.

### ISSUE THREAD

**Issue by imarceldoe** [ShadeAnimator/ShadeAnimator_Fallout4_AnimationKit#1]
When using a skeleton.hkx to generate a rig.txt, this occurs.

Any idea?

Reading file...
Traceback (most recent call last):
  File "F4AK_HKXPackUI\f4ak_hkxpack_UI.py", line 219, in generateRigTxt
  File "site-packages\bs4\__init__.py", line 156, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

**Comment by Dexesttp** [comment]
I think this is due to you not having any Python XML parsing libraries installed.

You can try installing lxml manually.  Grab it from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml) (first or second link, you'll probably want the 64x version), then run `pip install <filename>` to install it.

**Comment by imarceldoe** [comment]
Yeah, I did that along with installing BeautifulSoup4 just incase, tried with lxml‑3.7.3‑cp27‑cp27m‑win32.whl and restarted, no dice.

Reinstalled Python 2.7, Reinstalled Python 3.6 just incase -- nothing seems to work.

**Comment by ShadeAnimator** [comment]
In fact I did not update this repo in a long time, try the latest official version from nexus
http://www.nexusmods.com/fallout4/mods/16694/?

I stopped updated git, because I did not want to keep multiple places for people to download it from, and most modders are more familliar with nexus, rather than git.

However I may just leave the link on nexus and maybe pdf of the guide, while keeping all tools here.

Sorry for the inconvenience.

**Comment by ShadeAnimator** [comment]
And try using the .exe file instead of the .py file. If the error persists, then ill probbly need to switch from xml parser to simple html parser, i think they work essentially the same in this case.

**Comment by imarceldoe** [comment]
Yeah, I've been using the Nexus version. I just figured posting here might get your attention, opposed to posting on the nexus comments since I hadn't seen you active there for a while.

I think you'll have to switch it, I've been using the exe. It opens with an error: https://a.uguu.se/2k6PtdNewSsh_2017-03-18_18-29-59.png

I just ignore it and hit ok and it still works, everything seems to work minus a crash when converting hkx to fbx but then if you hit cancel the program will continue running and convert fine.

While I have your attention also, I would really appreciate it if you could take a look at: http://www.loverslab.com/topic/64567-fallout-4-animation-modding-for-modders-and-animators/page-15#entry1847676 post by xColour Theory for loading in creature skeletons.

**Comment by ShadeAnimator** [comment]
You figured out correctly, but not even because I am not active, I don't receive any notifications about comments. However I do receive notifications from LL and Nexus private messages, so you're safe to just drop me a note there.

The runtime error at the start is actually some build bug. When I used another machine to build it there was no error, but then I built new version on the other machine - and there's that bug. But from what I saw it did not actually influence anything.

And if you know a little python you could try to switch it yourself? You'll have to install all the dependencies, though, like BeautifulSoup and whatever else is used there. All you need to do is change "xml" to "html.parser"

I'm still in the middle of a lot of RL stuff, so I won't be able to fix any of it in about a month.

**Comment by imarceldoe** [comment]
I don't really know python that well, but I could give it a shot. I've dabbled in javascript at most.

File "F4AK_HKXPackUI\f4ak_hkxpack_UI.py", line 219, in generateRigTxt
File "site-packages\bs4_init_.py", line 156, in init

Is it just those lines I change or are there more?

Also is this where the dependencies are listed?
https://github.com/ShadeAnimator/ShadeAnimator_Fallout4_AnimationKit/blob/master/Tools/F4AK_HKXPackUI/build/hkxpack_based_tools_ui/warnhkxpack_based_tools_ui.txt

**Comment by ShadeAnimator** [comment]
just one line in f4ak_hkxpack_UI.py, it's line 219. soup = BeautifulSoup(fileData.read(), 'xml') should be replaced with 'html.parser' instead of 'xml'.
